name: lesson_tracker_pro
description: Lesson tracker MVP (Flutter)
publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

# Keep dependencies minimal for now; add as we implement features.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
    - assets/images/logo.png
    - assets/icons/
  fonts:
    - family: NotoSansSC
      fonts:
        - asset: web/assets/fonts/NotoSansSC-113.woff2
        - asset: web/assets/fonts/NotoSansSC-115.woff2
        - asset: web/assets/fonts/NotoSansSC-116.woff2
        - asset: web/assets/fonts/NotoSansSC-117.woff2
        - asset: web/assets/fonts/NotoSansSC-118.woff2
        - asset: web/assets/fonts/NotoSansSC-119.woff2
